.\" Copyright (c) 2025 impurify <have@anonymous.sex>.
.\"
.\" [REDACTED]
.\"
.Dd January 14, 2025
.Dt DOCUMENTWEB 7
.Os The Internet
.Sh NAME
.Nm The_Document_Web
.Nd The Web as it was intended.
.Sh SYNOPSIS
There are two competing visions of how the World Wide Web, and indeed,
the Internet should function:  The Apps Web, and
.Nm .
.Nm
foo bar.
.Sh MANIFESTO
xxx.
.Pp
yyy.
.Sh AUTHORS
.An impurify
.Aq have@anonymous.sex
