.\" Copyright (c) 2025 impurify <have@anonymous.sex>.
.\"
.\" [REDACTED]
.\"
.Dd January 14, 2025
.Dt KATEX 5
.Os The Internet
.Sh NAME
.Nm KaTeX
.Nd A LaTeX dialect for the Web
.Sh DESCRIPTION
.Nm
.Sh SEE ALSO
.Xr katex 5
.Xr lowdown 5
.Xr documentweb 7
.Sh AUTHORS
This manual page was written by
.An impurify
.Aq have@anonymous.sex ,
who has no affiliation to the
.Nm
authors.
